# Generated by Django 5.0 on 2024-03-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='test_pit',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
