# Generated by Django 5.0 on 2024-03-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_test_pit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address_project',
            field=models.CharField(default='n/a', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='coordinate_system',
            field=models.CharField(default='NAD83 New Jersey State Planes - US foot', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='excavation_method',
            field=models.CharField(default='n/a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='field_coordination',
            field=models.CharField(default='Regular traffic condition', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='lane_closure',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='material',
            field=models.CharField(default='Concrete duct', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='mpt',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='pavement_thickness',
            field=models.CharField(default='n/a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='pavement_type',
            field=models.CharField(default='n/a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='police_presence',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='recorded_size',
            field=models.CharField(default='8 inches', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='remarks',
            field=models.TextField(default='n/a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='utility_bottom_depth',
            field=models.IntegerField(default=42),
        ),
        migrations.AddField(
            model_name='report',
            name='utility_top_depth',
            field=models.IntegerField(default=36),
        ),
        migrations.AddField(
            model_name='report',
            name='utility_type',
            field=models.CharField(default='Water', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='utility_width',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(max_length=100),
        ),
    ]
