# Generated by Django 5.0.3 on 2024-03-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_project_address_project_report_coordinate_system_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='address_project',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='recorded_size',
            new_name='utility_size',
        ),
        migrations.RemoveField(
            model_name='report',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='field_coordinator',
            field=models.CharField(default='Paul Monteleone', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='tech_name',
            field=models.CharField(default='Paul Monteleone', max_length=200),
        ),
    ]
