# Generated by Django 5.0.3 on 2024-03-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_rename_address_project_project_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='after_excavation',
            field=models.ImageField(blank=True, null=True, upload_to='test_pits/'),
        ),
        migrations.AddField(
            model_name='report',
            name='before_excavation',
            field=models.ImageField(blank=True, null=True, upload_to='test_pits/'),
        ),
        migrations.AddField(
            model_name='report',
            name='excavated_area',
            field=models.ImageField(blank=True, null=True, upload_to='test_pits/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='remarks',
            field=models.TextField(max_length=200),
        ),
    ]
