# Generated by Django 5.0.3 on 2024-03-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_report_after_excavation_report_before_excavation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(default='0000', max_length=100),
        ),
    ]
