# Generated by Django 5.0.3 on 2024-03-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='project_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='report.project'),
        ),
    ]
