# Generated by Django 5.0.3 on 2024-03-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_report_project_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='test_pit',
            field=models.IntegerField(default=1),
        ),
    ]
