# Generated by Django 5.0.3 on 2024-03-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_report_test_pit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='after_excavation',
            field=models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='test_pits/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='before_excavation',
            field=models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='test_pits/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='excavated_area',
            field=models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='test_pits/'),
        ),
    ]
